name: TezDrop Vendor APK Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract ZIP
        run: unzip TezDrop_Vendor_Final.zip -d extracted
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: 'stable'
      - name: Build APK
        run: |
          cd extracted/final
          flutter pub get
          flutter build apk --debug --no-tree-shake-icons \
            --dart-define=FB_URL=https://tezdrop-84fb4-default-rtdb.firebaseio.com \
            --dart-define=OTP_KEY=6dda5f99-5a4a-11f1-8352-0200cd936042
      - uses: actions/upload-artifact@v4
        with:
          name: TezDrop-Vendor-APK
          path: extracted/final/build/app/outputs/flutter-apk/app-debug.apk
